version: '3'
services:
    
  postgres:
    image: postgres
    env_file:
      - .env
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - sail
    ports:
      - "127.0.0.1:5432:5432"
    restart: unless-stopped


  app:
    build:
      context: docker/app
    volumes:
      - ./internal:/internal
      - ./cert:/cert
    networks:
      - sail
    working_dir: /internal
    ports:
      - "127.0.0.1:3000:$PORT"
    environment:
      MYSQL_DSN: ""
    env_file:
      - .env
    depends_on:
      - postgres

networks:
    sail:
        external: true